---
http:
  routers:
    pfsense:
      rule: "Host(`pfsense.{{ domain }}`)"
      service: "pfsense"

  services:
    pfsense:
      loadBalancer:
        servers:
        - url: "https://pfsense.home.lan"
