---
http:
  routers:
    qbittorrent:
      rule: "Host(`qbittorrent.{{ domain }}`)"
      service: "qbittorrent"

  services:
    qbittorrent:
      loadBalancer:
        servers:
        - url: "http://seed.home.lan:8080"
