---
version: "2.1"

volumes:
  config:

networks:
  traefik-public:
    external: true

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:2.4.12
    container_name: heimdall
    networks:
      - traefik-public
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - config:/config
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.heimdall.loadbalancer.server.port=443"
      - "traefik.http.services.heimdall.loadbalancer.server.scheme=https"
      - "homelab.sub-domain=heimdall"
