- hosts: all
  become: yes
  roles:
    - common/infra

#- hosts: plex
#  become: yes
#  roles:
#    - { role: common/storage, shares: "{{plex_shares}}" }
#    - plex

- hosts: compute
  become: yes
  roles:
    - common/docker
    - { role: deployment, project: traefik, networks: [ "traefik-public" ] }
    - { role: deployment, project: monitoring }
    - { role: deployment, project: hass }
    - { role: deployment, project: unifi }
    - { role: deployment, project: heimdall }