- hosts: all
  become: yes
  roles:
    - common/infrastructure

- hosts: plex
  become: yes
  roles:
    - common/storage
    - plex

- hosts: compute
  become: yes
  roles:
    - common/docker
    - { role: deployment, project: traefik }
    - { role: deployment, project: hass }
    - { role: deployment, project: nextcloud }
    - { role: deployment, project: unifi }
    - { role: deployment, project: heimdall }