- hosts: all
  become: yes
  roles:
    - common/infrastructure

- hosts: plex
  become: yes
  roles:
    - common/storage
    - plex

- hosts: compute
  become: yes
  roles:
    - common/docker
    - { role: deployment, project: traefik, networks: [ "traefik-public" ] }
    - { role: deployment, project: monitoring }
    - { role: deployment, project: hass }
    - { role: deployment, project: unifi }
    - { role: deployment, project: heimdall }
    - { role: deployment, project: experiments }