---
version: "3.9"

networks:
  loki: {}
  traefik-public:
    external: true

volumes:
  grafana_logs: {}
  grafana_storage: {}
  loki_storage: {}

services:
  loki:
    image: grafana/loki:2.5.0
    restart: unless-stopped
    networks:
      - loki
    volumes:
      - "loki_storage:/loki"
    ports:
      - "3100:3100"

  grafana:
    image: grafana/grafana-oss:8.5.3
    restart: unless-stopped
    networks:
      - loki
      - traefik-public
    volumes:
      - "grafana_logs:/logs"
      - "grafana_storage:/var/lib/grafana"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "homelab.sub-domain=monitoring"
    depends_on:
      - loki
