---
version: "3.9"

volumes:
  config:

services:
  # https://hub.docker.com/r/linuxserver/qbittorrent
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.5.2
    container_name: qbittorrent
    environment:
      - PUID=3001
      - PGID=3001
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - "/mnt/seed/downloads:/downloads"
      - "config:/config"
    restart: unless-stopped
