http:
  routers:
    nextcloud:
      rule: "Host(`nextcloud.{{ domain }}`)"
      service: "nextcloud"

  services:
    nextcloud:
      loadBalancer:
        servers:
        - url: "https://{{ storage_host }}:8282"
