---
- name: Create service directory
  file:
    path: "{{ docker_compose_dir }}/nextcloud"
    state: directory

- name: Copy services configuration
  template:
    src: files/nextcloud/docker-compose.yml
    dest: "{{ docker_compose_dir }}/nextcloud/docker-compose.yml"

- name: Start services
  community.docker.docker_compose:
    project_src: "{{ docker_compose_dir }}/nextcloud"
    restarted: yes