---
- name: Install qemu-guest-agent
  apt:
    name: qemu-guest-agent
    state: present
    update_cache: yes
  notify: reboot system

- name: Install management utilities
  apt:
    name:
      - htop
    state: present
