---
- name: Create networks
  community.docker.docker_network:
    name: "{{ item }}"
    state: present
  with_items: "{{ networks | default([]) }}"
  tags: deployment

- name: Create {{ project }} root directory
  file:
    path: "{{ docker_compose_dir }}/{{ project }}"
    state: directory
  tags: deployment

- name: Create {{ project }} sub directories
  file:
    path: "{{ docker_compose_dir }}/{{ project }}/{{ item.path }}"
    state: directory
    recurse: true
  with_community.general.filetree: "{{ project }}/"
  when: item.state == 'directory'
  tags: deployment

- name: Template {{ project }} configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ docker_compose_dir }}/{{ project }}/{{ item.path }}"
  with_community.general.filetree: "{{ project }}/"
  when: item.state == 'file'
  tags: deployment
  notify: restart project
