---
- name: Create {{ project }} directories
  file:
    path: "{{ docker_compose_dir }}/{{ project }}/{{ item.path }}"
    state: directory
    recurse: true
  with_community.general.filetree: "{{ project }}/"
  when: item.state == 'directory'
  tags: deployment

- name: Template {{ project }} configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ docker_compose_dir }}/{{ project }}/{{ item.path }}"
  with_community.general.filetree: "{{ project }}/"
  when: item.state == 'file'
  tags: deployment
  notify: restart project
