---
- name: Allow apt to use a repository over HTTPS
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Install docker official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker stable repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    update_cache: yes

- name: Install docker engine
  apt:
    name:
      - docker-ce
      - docker-ce-cli
    state: present

- name: Install pip
  apt:
    name: python3-pip
    state: present

- name: Install docker modules for python
  pip:
    name:
      - docker
      - docker-compose
    state: present
