---
- name: Install plex signing key
  apt_key:
    url: https://downloads.plex.tv/plex-keys/PlexSign.key
    state: present

- name: Configure plex apt repository
  apt_repository:
    repo: deb https://downloads.plex.tv/repo/deb public main
    state: present
    update_cache: yes

- name: Install plex
  apt:
    name: plexmediaserver
    state: present

- name: Copy plex ufw configuration file
  copy:
    src: files/plexmediaserver
    dest: /etc/ufw/applications.d/plexmediaserver

- name: Enable plex ufw rules
  ufw:
    name: plexmediaserver-all
    rule: allow
