---
- name: Install NFS commons
  apt:
    name: nfs-common

- name: Create storage group
  group:
    name: "{{ storage.user.name }}"
    gid: "{{ storage.user.gid }}"
    state: present

- name: Create storage user
  user:
    name: "{{ storage.user.name }}"
    group: "{{ storage.user.name }}"
    uid: "{{ storage.user.uid }}"
    state: present

- name: Create mount path
  file:
    path: "{{ storage.share.mount }}"
    state: directory
    recurse: yes

- name: Mount shares
  mount:
    state: mounted
    fstype: nfs
    path: "{{ storage.share.mount }}"
    src: "{{ storage.share.src }}"
    opts: rw,nolock

- name: Create share directories
  file:
    path: "{{ storage.share.mount }}/{{ item }}"
    owner: "{{ storage.user.name }}"
    group: "{{ storage.user.name }}"
    state: directory
    recurse: yes
  loop: "{{ storage.directories }}"
