---
- name: Install NFS commons
  apt:
    name: nfs-common

- name: Create storage group
  group:
    name: "{{ owner.name }}"
    gid: "{{ owner.gid }}"
    state: present

- name: Create storage user
  user:
    name: "{{ owner.name }}"
    group: "{{ owner.name }}"
    uid: "{{ owner.uid }}"
    state: present

- name: Create mount path
  file:
    path: "{{ share.mount }}"
    state: directory
    recurse: yes

- name: Mount shares
  mount:
    state: mounted
    fstype: nfs
    path: "{{ share.mount }}"
    src: "{{ share.src }}"
    opts: rw,nolock

- name: Create share {{ item }} directory
  file:
    path: "{{ share.mount }}/{{ item }}"
    owner: "{{ owner.name }}"
    group: "{{ owner.name }}"
    state: directory
    recurse: yes
  with_items: "{{ directories | default('[]') }}"
